### ISSUE TITLE
How can I convert BEAT bvh file to SMPL with this method?

### ISSUE THREAD

**Issue by hhq111** [EmptyBlueBox/BVH2SMPL#1]
Thank you very much for providing this method! 

I would like to ask how can I convert BEAT bvh file to SMPL. I use this method and change the corresponding mapping, but the motion I 

get is different from the template bvh file.

Could you give me some advice?

Thank you!

**Comment by EmptyBlueBox** [comment]
I'm so sorry that I haven't used a BEAT bvh file, but the retargeting process can sometimes change the skeleton. It's common that your result is different from your input bvh file.

**Comment by hhq111** [comment]
Thanks for your reply very much! I wonder what dataset you used about your bvh file. Could you tell me please?



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/24/2024 00:13 |
| To | ***@***.***> |
| Cc | HaiQin ***@***.***>***@***.***> |
| Subject | Re: [EmptyBlueBox/BVH2SMPL] How can I convert BEAT bvh file to SMPL with this method? (Issue #1) |

I'm so sorry that I haven't used a BEAT bvh file, but the retargeting process can sometimes change the skeleton. It's common that your result is different from your input bvh file.

**Comment by EmptyBlueBox** [comment]
Oh so sorry I can't remember. 🥲

**Comment by hhq111** [comment]
It doesn't matter. Thank you extremely! I will try to solve this problem.



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/24/2024 00:24 |
| To | ***@***.***> |
| Cc | HaiQin ***@***.***>***@***.***> |
| Subject | Re: [EmptyBlueBox/BVH2SMPL] How can I convert BEAT bvh file to SMPL with this method? (Issue #1) |

Oh so sorry I can't remember. 🥲

**Comment by EmptyBlueBox** [comment]
You're welcome!
